
# This file is automatically generated, you probably don't want to edit this

mvntestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mvntestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            mvnTest = "hz",
            univariateTest = "AD",
            showDescriptives = TRUE,
            outlierMethod = "none",
            outlierAlpha = 0.05,
            transform = "none",
            powerFamily = "none",
            scale = FALSE,
            impute = "none",
            bootstrap = FALSE,
            nBoot = 1000,
            showQQPlot = FALSE,
            showUniPlots = FALSE,
            showBoxPlots = FALSE,
            showHistograms = FALSE, ...) {

            super$initialize(
                package="MVN",
                name="mvntest",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..mvnTest <- jmvcore::OptionList$new(
                "mvnTest",
                mvnTest,
                options=list(
                    "hz",
                    "mardia",
                    "hw",
                    "royston",
                    "doornik_hansen",
                    "energy"),
                default="hz")
            private$..univariateTest <- jmvcore::OptionList$new(
                "univariateTest",
                univariateTest,
                options=list(
                    "AD",
                    "SW",
                    "SF",
                    "CVM",
                    "Lillie"),
                default="AD")
            private$..showDescriptives <- jmvcore::OptionBool$new(
                "showDescriptives",
                showDescriptives,
                default=TRUE)
            private$..outlierMethod <- jmvcore::OptionList$new(
                "outlierMethod",
                outlierMethod,
                options=list(
                    "none",
                    "quan",
                    "adj"),
                default="none")
            private$..outlierAlpha <- jmvcore::OptionNumber$new(
                "outlierAlpha",
                outlierAlpha,
                min=0.001,
                max=0.5,
                default=0.05)
            private$..transform <- jmvcore::OptionList$new(
                "transform",
                transform,
                options=list(
                    "none",
                    "log",
                    "sqrt",
                    "square"),
                default="none")
            private$..powerFamily <- jmvcore::OptionList$new(
                "powerFamily",
                powerFamily,
                options=list(
                    "none",
                    "bcPower",
                    "bcnPower",
                    "yjPower"),
                default="none")
            private$..scale <- jmvcore::OptionBool$new(
                "scale",
                scale,
                default=FALSE)
            private$..impute <- jmvcore::OptionList$new(
                "impute",
                impute,
                options=list(
                    "none",
                    "mean",
                    "median",
                    "mice"),
                default="none")
            private$..bootstrap <- jmvcore::OptionBool$new(
                "bootstrap",
                bootstrap,
                default=FALSE)
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                min=100,
                max=100000,
                default=1000)
            private$..showQQPlot <- jmvcore::OptionBool$new(
                "showQQPlot",
                showQQPlot,
                default=FALSE)
            private$..showUniPlots <- jmvcore::OptionBool$new(
                "showUniPlots",
                showUniPlots,
                default=FALSE)
            private$..showBoxPlots <- jmvcore::OptionBool$new(
                "showBoxPlots",
                showBoxPlots,
                default=FALSE)
            private$..showHistograms <- jmvcore::OptionBool$new(
                "showHistograms",
                showHistograms,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..mvnTest)
            self$.addOption(private$..univariateTest)
            self$.addOption(private$..showDescriptives)
            self$.addOption(private$..outlierMethod)
            self$.addOption(private$..outlierAlpha)
            self$.addOption(private$..transform)
            self$.addOption(private$..powerFamily)
            self$.addOption(private$..scale)
            self$.addOption(private$..impute)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..showQQPlot)
            self$.addOption(private$..showUniPlots)
            self$.addOption(private$..showBoxPlots)
            self$.addOption(private$..showHistograms)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        mvnTest = function() private$..mvnTest$value,
        univariateTest = function() private$..univariateTest$value,
        showDescriptives = function() private$..showDescriptives$value,
        outlierMethod = function() private$..outlierMethod$value,
        outlierAlpha = function() private$..outlierAlpha$value,
        transform = function() private$..transform$value,
        powerFamily = function() private$..powerFamily$value,
        scale = function() private$..scale$value,
        impute = function() private$..impute$value,
        bootstrap = function() private$..bootstrap$value,
        nBoot = function() private$..nBoot$value,
        showQQPlot = function() private$..showQQPlot$value,
        showUniPlots = function() private$..showUniPlots$value,
        showBoxPlots = function() private$..showBoxPlots$value,
        showHistograms = function() private$..showHistograms$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..mvnTest = NA,
        ..univariateTest = NA,
        ..showDescriptives = NA,
        ..outlierMethod = NA,
        ..outlierAlpha = NA,
        ..transform = NA,
        ..powerFamily = NA,
        ..scale = NA,
        ..impute = NA,
        ..bootstrap = NA,
        ..nBoot = NA,
        ..showQQPlot = NA,
        ..showUniPlots = NA,
        ..showBoxPlots = NA,
        ..showHistograms = NA)
)

mvntestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mvntestResults",
    inherit = jmvcore::Group,
    active = list(
        mvnTable = function() private$.items[["mvnTable"]],
        uniTable = function() private$.items[["uniTable"]],
        descTable = function() private$.items[["descTable"]],
        outlierTable = function() private$.items[["outlierTable"]],
        qqPlot = function() private$.items[["qqPlot"]],
        uniPlots = function() private$.items[["uniPlots"]],
        boxPlots = function() private$.items[["boxPlots"]],
        histPlots = function() private$.items[["histPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariate Normality Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="mvnTable",
                title="Multivariate Normality Test",
                rows=0,
                visible=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "mvnTest",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute",
                    "bootstrap",
                    "nBoot"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="result", 
                        `title`="Result", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="uniTable",
                title="Univariate Normality Tests",
                rows=0,
                visible=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "univariateTest",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="normality", 
                        `title`="Normality", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descTable",
                title="Descriptive Statistics",
                rows=0,
                visible="(showDescriptives)",
                clearWith=list(
                    "vars",
                    "group",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="Std. Dev.", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="q25", 
                        `title`="25th", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="q75", 
                        `title`="75th", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="skew", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="kurtosis", 
                        `title`="Kurtosis", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierTable",
                title="Multivariate Outliers",
                rows=0,
                visible="(outlierMethod:quan || outlierMethod:adj)",
                clearWith=list(
                    "vars",
                    "group",
                    "outlierMethod",
                    "outlierAlpha",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="obs", 
                        `title`="Observation", 
                        `type`="integer"),
                    list(
                        `name`="mahal", 
                        `title`="Mahalanobis Distance", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqPlot",
                title="Multivariate Q-Q Plot",
                width=500,
                height=400,
                renderFun=".qqPlot",
                visible="(showQQPlot)",
                clearWith=list(
                    "vars",
                    "group",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute")))
            self$add(jmvcore::Image$new(
                options=options,
                name="uniPlots",
                title="Univariate Q-Q Plots",
                width=600,
                height=400,
                renderFun=".uniQQPlots",
                visible="(showUniPlots)",
                clearWith=list(
                    "vars",
                    "group",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute")))
            self$add(jmvcore::Image$new(
                options=options,
                name="boxPlots",
                title="Box Plots",
                width=600,
                height=400,
                renderFun=".boxPlots",
                visible="(showBoxPlots)",
                clearWith=list(
                    "vars",
                    "group",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute")))
            self$add(jmvcore::Image$new(
                options=options,
                name="histPlots",
                title="Histograms",
                width=600,
                height=400,
                renderFun=".histPlots",
                visible="(showHistograms)",
                clearWith=list(
                    "vars",
                    "group",
                    "transform",
                    "powerFamily",
                    "scale",
                    "impute")))}))

mvntestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mvntestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MVN",
                name = "mvntest",
                version = c(6,3,0),
                options = options,
                results = mvntestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multivariate Normality Test
#'
#' 
#' @param data .
#' @param vars Numeric variables to test for multivariate normality.
#' @param group Optional grouping variable for stratified analysis.
#' @param mvnTest The multivariate normality test to use.
#' @param univariateTest The univariate normality test to apply to each
#'   variable.
#' @param showDescriptives Show descriptive statistics table.
#' @param outlierMethod Method for detecting multivariate outliers using
#'   robust Mahalanobis distance.
#' @param outlierAlpha Significance level for outlier detection.
#' @param transform Marginal transformation to apply to each variable.
#' @param powerFamily Power transformation family to apply before analysis.
#' @param scale Standardize data (zero mean, unit variance) before analysis.
#' @param impute Method for handling missing data.
#' @param bootstrap Use bootstrap resampling for p-value estimation.
#' @param nBoot Number of bootstrap replicates.
#' @param showQQPlot Show chi-square Q-Q plot for multivariate normality
#'   assessment.
#' @param showUniPlots Show univariate Q-Q plots for each variable.
#' @param showBoxPlots Show box plots for each variable.
#' @param showHistograms Show histograms with normal curve overlay.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mvnTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$uniTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outlierTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$uniPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$boxPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$histPlots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mvnTable$asDF}
#'
#' \code{as.data.frame(results$mvnTable)}
#'
#' @export
mvntest <- function(
    data,
    vars,
    group = NULL,
    mvnTest = "hz",
    univariateTest = "AD",
    showDescriptives = TRUE,
    outlierMethod = "none",
    outlierAlpha = 0.05,
    transform = "none",
    powerFamily = "none",
    scale = FALSE,
    impute = "none",
    bootstrap = FALSE,
    nBoot = 1000,
    showQQPlot = FALSE,
    showUniPlots = FALSE,
    showBoxPlots = FALSE,
    showHistograms = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mvntest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mvntestOptions$new(
        vars = vars,
        group = group,
        mvnTest = mvnTest,
        univariateTest = univariateTest,
        showDescriptives = showDescriptives,
        outlierMethod = outlierMethod,
        outlierAlpha = outlierAlpha,
        transform = transform,
        powerFamily = powerFamily,
        scale = scale,
        impute = impute,
        bootstrap = bootstrap,
        nBoot = nBoot,
        showQQPlot = showQQPlot,
        showUniPlots = showUniPlots,
        showBoxPlots = showBoxPlots,
        showHistograms = showHistograms)

    analysis <- mvntestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

